<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder {

	public function run()
	{
		DB::table('countries')->delete();

        DB::table('countries')->insert([
			['id' => 1, 'title' => 'Brasil'],
			/*['id' => 2, 'title' => 'United States'],
			['id' => null, 'title' => 'Canada'],
			['id' => null, 'title' => 'Afghanistan'],
			['id' => null, 'title' => 'Albania'],
			['id' => null, 'title' => 'Algeria'],
			['id' => null, 'title' => 'American Samoa'],
			['id' => null, 'title' => 'Andorra'],
			['id' => null, 'title' => 'Angola'],
			['id' => null, 'title' => 'Anguilla'],
			['id' => null, 'title' => 'Antarctica'],
			['id' => null, 'title' => 'Antigua and/or Barbuda'],
			['id' => null, 'title' => 'Argentina'],
			['id' => null, 'title' => 'Armenia'],
			['id' => null, 'title' => 'Aruba'],
			['id' => null, 'title' => 'Australia'],
			['id' => null, 'title' => 'Austria'],
			['id' => null, 'title' => 'Azerbaijan'],
			['id' => null, 'title' => 'Bahamas'],
			['id' => null, 'title' => 'Bahrain'],
			['id' => null, 'title' => 'Bangladesh'],
			['id' => null, 'title' => 'Barbados'],
			['id' => null, 'title' => 'Belarus'],
			['id' => null, 'title' => 'Belgium'],
			['id' => null, 'title' => 'Belize'],
			['id' => null, 'title' => 'Benin'],
			['id' => null, 'title' => 'Bermuda'],
			['id' => null, 'title' => 'Bhutan'],
			['id' => null, 'title' => 'Bolivia'],
			['id' => null, 'title' => 'Bosnia and Herzegovina'],
			['id' => null, 'title' => 'Botswana'],
			['id' => null, 'title' => 'Bouvet Island'],
			['id' => null, 'title' => 'British lndian Ocean Territory'],
			['id' => null, 'title' => 'Brunei Darussalam'],
			['id' => null, 'title' => 'Bulgaria'],
			['id' => null, 'title' => 'Burkina Faso'],
			['id' => null, 'title' => 'Burundi'],
			['id' => null, 'title' => 'Cambodia'],
			['id' => null, 'title' => 'Cameroon'],
			['id' => null, 'title' => 'Cape Verde'],
			['id' => null, 'title' => 'Cayman Islands'],
			['id' => null, 'title' => 'Central African Republic'],
			['id' => null, 'title' => 'Chad'],
			['id' => null, 'title' => 'Chile'],
			['id' => null, 'title' => 'China'],
			['id' => null, 'title' => 'Christmas Island'],
			['id' => null, 'title' => 'Cocos (Keeling] Islands'],
			['id' => null, 'title' => 'Colombia'],
			['id' => null, 'title' => 'Comoros'],
			['id' => null, 'title' => 'Congo'],
			['id' => null, 'title' => 'Cook Islands'],
			['id' => null, 'title' => 'Costa Rica'],
			['id' => null, 'title' => 'Croatia (Hrvatska]'],
			['id' => null, 'title' => 'Cuba'],
			['id' => null, 'title' => 'Cyprus'],
			['id' => null, 'title' => 'Czech Republic'],
			['id' => null, 'title' => 'Democratic Republic of Congo'],
			['id' => null, 'title' => 'Denmark'],
			['id' => null, 'title' => 'Djibouti'],
			['id' => null, 'title' => 'Dominica'],
			['id' => null, 'title' => 'Dominican Republic'],
			['id' => null, 'title' => 'East Timor'],
			['id' => null, 'title' => 'Ecudaor'],
			['id' => null, 'title' => 'Egypt'],
			['id' => null, 'title' => 'El Salvador'],
			['id' => null, 'title' => 'Equatorial Guinea'],
			['id' => null, 'title' => 'Eritrea'],
			['id' => null, 'title' => 'Estonia'],
			['id' => null, 'title' => 'Ethiopia'],
			['id' => null, 'title' => 'Falkland Islands (Malvinas]'],
			['id' => null, 'title' => 'Faroe Islands'],
			['id' => null, 'title' => 'Fiji'],
			['id' => null, 'title' => 'Finland'],
			['id' => null, 'title' => 'France'],
			['id' => null, 'title' => 'France, Metropolitan'],
			['id' => null, 'title' => 'French Guiana'],
			['id' => null, 'title' => 'French Polynesia'],
			['id' => null, 'title' => 'French Southern Territories'],
			['id' => null, 'title' => 'Gabon'],
			['id' => null, 'title' => 'Gambia'],
			['id' => null, 'title' => 'Georgia'],
			['id' => null, 'title' => 'Germany'],
			['id' => null, 'title' => 'Ghana'],
			['id' => null, 'title' => 'Gibraltar'],
			['id' => null, 'title' => 'Greece'],
			['id' => null, 'title' => 'Greenland'],
			['id' => null, 'title' => 'Grenada'],
			['id' => null, 'title' => 'Guadeloupe'],
			['id' => null, 'title' => 'Guam'],
			['id' => null, 'title' => 'Guatemala'],
			['id' => null, 'title' => 'Guinea'],
			['id' => null, 'title' => 'Guinea-Bissau'],
			['id' => null, 'title' => 'Guyana'],
			['id' => null, 'title' => 'Haiti'],
			['id' => null, 'title' => 'Heard and Mc Donald Islands'],
			['id' => null, 'title' => 'Honduras'],
			['id' => null, 'title' => 'Hong Kong'],
			['id' => null, 'title' => 'Hungary'],
			['id' => null, 'title' => 'Iceland'],
			['id' => null, 'title' => 'India'],
			['id' => null, 'title' => 'Indonesia'],
			['id' => null, 'title' => 'Iran (Islamic Republic of]'],
			['id' => null, 'title' => 'Iraq'],
			['id' => null, 'title' => 'Ireland'],
			['id' => null, 'title' => 'Israel'],
			['id' => null, 'title' => 'Italy'],
			['id' => null, 'title' => 'Ivory Coast'],
			['id' => null, 'title' => 'Jamaica'],
			['id' => null, 'title' => 'Japan'],
			['id' => null, 'title' => 'Jordan'],
			['id' => null, 'title' => 'Kazakhstan'],
			['id' => null, 'title' => 'Kenya'],
			['id' => null, 'title' => 'Kiribati'],
			['id' => null, 'title' => 'Korea, Democratic People\'s Republic of'],
			['id' => null, 'title' => 'Korea, Republic of'],
			['id' => null, 'title' => 'Kuwait'],
			['id' => null, 'title' => 'Kyrgyzstan'],
			['id' => null, 'title' => 'Lao People\'s Democratic Republic'],
			['id' => null, 'title' => 'Latvia'],
			['id' => null, 'title' => 'Lebanon'],
			['id' => null, 'title' => 'Lesotho'],
			['id' => null, 'title' => 'Liberia'],
			['id' => null, 'title' => 'Libyan Arab Jamahiriya'],
			['id' => null, 'title' => 'Liechtenstein'],
			['id' => null, 'title' => 'Lithuania'],
			['id' => null, 'title' => 'Luxembourg'],
			['id' => null, 'title' => 'Macau'],
			['id' => null, 'title' => 'Macedonia'],
			['id' => null, 'title' => 'Madagascar'],
			['id' => null, 'title' => 'Malawi'],
			['id' => null, 'title' => 'Malaysia'],
			['id' => null, 'title' => 'Maldives'],
			['id' => null, 'title' => 'Mali'],
			['id' => null, 'title' => 'Malta'],
			['id' => null, 'title' => 'Marshall Islands'],
			['id' => null, 'title' => 'Martinique'],
			['id' => null, 'title' => 'Mauritania'],
			['id' => null, 'title' => 'Mauritius'],
			['id' => null, 'title' => 'Mayotte'],
			['id' => null, 'title' => 'Mexico'],
			['id' => null, 'title' => 'Micronesia, Federated States of'],
			['id' => null, 'title' => 'Moldova, Republic of'],
			['id' => null, 'title' => 'Monaco'],
			['id' => null, 'title' => 'Mongolia'],
			['id' => null, 'title' => 'Montserrat'],
			['id' => null, 'title' => 'Morocco'],
			['id' => null, 'title' => 'Mozambique'],
			['id' => null, 'title' => 'Myanmar'],
			['id' => null, 'title' => 'Namibia'],
			['id' => null, 'title' => 'Nauru'],
			['id' => null, 'title' => 'Nepal'],
			['id' => null, 'title' => 'Netherlands'],
			['id' => null, 'title' => 'Netherlands Antilles'],
			['id' => null, 'title' => 'New Caledonia'],
			['id' => null, 'title' => 'New Zealand'],
			['id' => null, 'title' => 'Nicaragua'],
			['id' => null, 'title' => 'Niger'],
			['id' => null, 'title' => 'Nigeria'],
			['id' => null, 'title' => 'Niue'],
			['id' => null, 'title' => 'Norfork Island'],
			['id' => null, 'title' => 'Northern Mariana Islands'],
			['id' => null, 'title' => 'Norway'],
			['id' => null, 'title' => 'Oman'],
			['id' => null, 'title' => 'Pakistan'],
			['id' => null, 'title' => 'Palau'],
			['id' => null, 'title' => 'Panama'],
			['id' => null, 'title' => 'Papua New Guinea'],
			['id' => null, 'title' => 'Paraguay'],
			['id' => null, 'title' => 'Peru'],
			['id' => null, 'title' => 'Philippines'],
			['id' => null, 'title' => 'Pitcairn'],
			['id' => null, 'title' => 'Poland'],
			['id' => null, 'title' => 'Portugal'],
			['id' => null, 'title' => 'Puerto Rico'],
			['id' => null, 'title' => 'Qatar'],
			['id' => null, 'title' => 'Republic of South Sudan'],
			['id' => null, 'title' => 'Reunion'],
			['id' => null, 'title' => 'Romania'],
			['id' => null, 'title' => 'Russian Federation'],
			['id' => null, 'title' => 'Rwanda'],
			['id' => null, 'title' => 'Saint Kitts and Nevis'],
			['id' => null, 'title' => 'Saint Lucia'],
			['id' => null, 'title' => 'Saint Vincent and the Grenadines'],
			['id' => null, 'title' => 'Samoa'],
			['id' => null, 'title' => 'San Marino'],
			['id' => null, 'title' => 'Sao Tome and Principe'],
			['id' => null, 'title' => 'Saudi Arabia'],
			['id' => null, 'title' => 'Senegal'],
			['id' => null, 'title' => 'Serbia'],
			['id' => null, 'title' => 'Seychelles'],
			['id' => null, 'title' => 'Sierra Leone'],
			['id' => null, 'title' => 'Singapore'],
			['id' => null, 'title' => 'Slovakia'],
			['id' => null, 'title' => 'Slovenia'],
			['id' => null, 'title' => 'Solomon Islands'],
			['id' => null, 'title' => 'Somalia'],
			['id' => null, 'title' => 'South Africa'],
			['id' => null, 'title' => 'South Georgia South Sandwich Islands'],
			['id' => null, 'title' => 'Spain'],
			['id' => null, 'title' => 'Sri Lanka'],
			['id' => null, 'title' => 'St. Helena'],
			['id' => null, 'title' => 'St. Pierre and Miquelon'],
			['id' => null, 'title' => 'Sudan'],
			['id' => null, 'title' => 'Suriname'],
			['id' => null, 'title' => 'Svalbarn and Jan Mayen Islands'],
			['id' => null, 'title' => 'Swaziland'],
			['id' => null, 'title' => 'Sweden'],
			['id' => null, 'title' => 'Switzerland'],
			['id' => null, 'title' => 'Syrian Arab Republic'],
			['id' => null, 'title' => 'Taiwan'],
			['id' => null, 'title' => 'Tajikistan'],
			['id' => null, 'title' => 'Tanzania, United Republic of'],
			['id' => null, 'title' => 'Thailand'],
			['id' => null, 'title' => 'Togo'],
			['id' => null, 'title' => 'Tokelau'],
			['id' => null, 'title' => 'Tonga'],
			['id' => null, 'title' => 'Trinidad and Tobago'],
			['id' => null, 'title' => 'Tunisia'],
			['id' => null, 'title' => 'Turkey'],
			['id' => null, 'title' => 'Turkmenistan'],
			['id' => null, 'title' => 'Turks and Caicos Islands'],
			['id' => null, 'title' => 'Tuvalu'],
			['id' => null, 'title' => 'Uganda'],
			['id' => null, 'title' => 'Ukraine'],
			['id' => null, 'title' => 'United Arab Emirates'],
			['id' => null, 'title' => 'United Kingdom'],
			['id' => null, 'title' => 'United States minor outlying islands'],
			['id' => null, 'title' => 'Uruguay'],
			['id' => null, 'title' => 'Uzbekistan'],
			['id' => null, 'title' => 'Vanuatu'],
			['id' => null, 'title' => 'Vatican City State'],
			['id' => null, 'title' => 'Venezuela'],
			['id' => null, 'title' => 'Vietnam'],
			['id' => null, 'title' => 'Virgin Islands (British]'],
			['id' => null, 'title' => 'Virgin Islands (U.S.]'],
			['id' => null, 'title' => 'Wallis and Futuna Islands'],
			['id' => null, 'title' => 'Western Sahara'],
			['id' => null, 'title' => 'Yemen'],
			['id' => null, 'title' => 'Yugoslavia'],
			['id' => null, 'title' => 'Zaire'],
			['id' => null, 'title' => 'Zambia'],
			['id' => null, 'title' => 'Zimbabwe'], */
        ]);
	}
}
